### ISSUE TITLE
How does this work on iOS

### ISSUE THREAD

**Issue by animeshjain** [boyan01/system_clock#1]
I looked at the code but could not figure out

**Comment by boyan01** [comment]
It is powered by dart ffi.  you can check more information here:
https://flutter.dev/docs/development/platform-integration/c-interop#ios-and-macos

**Comment by animeshjain** [comment]
Ok. When I run it on iOS I get an error though

1 warning generated.
/Users/XXXX/.pub-cache/hosted/pub.dartlang.org/system_clock-0.5.0/ios/Classes/system_clock.cpp:1:10: fatal error: 'include/system_clock.h' file not found
#include "include/system_clock.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Also, looking at system_clock.cpp, I am not able to understand which underlying iOS API is being called to get the system time?

Appreciate your help.

**Comment by boyan01** [comment]
seems that new iOS build tools break the c++ build.

I will modify the logic of include to fix this problem later.

**Comment by animeshjain** [comment]
cool! Look forward to your fix and trying it out.

**Comment by boyan01** [comment]
Please take a try for version 0.6.0 .  

I add a placeholder header file for system_clock.mm , it works fine for me.

**Comment by animeshjain** [comment]
Worked! 

PS. Filing a separate issue for Android - build failed on Android now 😐
