### ISSUE TITLE
Android build failure (v0.6.0)

### ISSUE THREAD

**Issue by animeshjain** [boyan01/system_clock#2]
Getting the following...

Let me know what I can provide to help debug

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/XXXX/.pub-cache/hosted/pub.dartlang.org/system_clock-0.6.0/android/build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':system_clock'.
> Could not find method buildFeatures() for arguments [build_aw35n6snm0achvqawoa63ydiu$_run_closure2$_closure8@e7263b4] on object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Exception: Gradle task assembleStagingDebug failed with exit code 1
```

**Comment by animeshjain** [comment]
I tried this on an Android device running Android 6

`• A0001 (mobile)                 • 2b214b17                                 • android-arm • Android 6.0.1 (API 23)`

**Comment by animeshjain** [comment]
Same with a more recent Android

`• ONEPLUS A5010 (mobile)         • 23dad98b                                 • android-arm64 • Android 8.1.0 (API 27)`

**Comment by boyan01** [comment]
This error occurred because your app agp version lower than 4.0.0

Maybe I should decrease this library's agp version to 3.5.1

----

Which agp is Android Gradle Plugin.

Animesh Jain <notifications@github.com> 于 2020年9月28日周一 22:20写道：

**Comment by animeshjain** [comment]
In my build.gradle, it says
`classpath 'com.android.tools.build:gradle:3.6.3'`

In my gradle-wrapper.properties it says
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

**Comment by animeshjain** [comment]
You are right, I changed my gradle version to 4.0.0 and it is now working 👍 

I am not sure about the intricacies of Gradle, but I guess if a lower version can also work, it might be worth trying that as Flutter scaffolding is creating projects with `classpath 'com.android.tools.build:gradle:3.5.0'` as of now I think.

**Comment by boyan01** [comment]
version 0.7.0 should fixes this. I lowered the android gradle plugin version requirement of the library
