### ISSUE TITLE
On Linux, system_clock_uptime not found when running tests

### ISSUE THREAD

**Issue by oSoMoN** [boyan01/system_clock#5]
I'm using `SystemClock.uptime()` in a project, but when I write tests that exercise the function calling it, I'm getting the following failure:

    Invalid argument(s): Failed to lookup symbol 'system_clock_uptime': /home/osomon/build/flutter/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester: undefined symbol: system_clock_uptime
    dart:ffi                                                                DynamicLibrary.lookup
    package:system_clock/src/clock_io.dart 8:18                             _lookupClockFunc
    package:system_clock/src/clock_io.dart 38:5                             _uptime
    package:system_clock/src/clock_io.dart                                  _uptime
    package:system_clock/src/clock_io.dart 46:33                            uptime
    package:system_clock/system_clock.dart 15:18                            SystemClock.uptime

Tests are written using the standard `flutter_test` library, and run with `flutter test`.

And indeed, if I call the following in my test function, it returns `false`, whereas when the code is run from an application, it returns `true`:

```dart
DynamicLibrary.process().providesSymbol('system_clock_uptime')
```

**Comment by boyan01** [comment]
Flutter test (not integration_test) only load dart code, so there is no `system_clock_uptime` symbol when test running.

https://github.com/dart-lang/ffi/issues/39#issuecomment-627384593

flutter integration_test should be work.
