### ISSUE TITLE
Failed to load dynamic library 'system_clock_plugin.dll'

### ISSUE THREAD

**Issue by gaddlord** [boyan01/system_clock#8]
In pubspec.yaml I have "system_clock: ^1.2.0".

When I call:

    SystemClock.uptime()

I am getting "Invalid argument(s): Failed to load dynamic library 'system_clock_plugin.dll': error code 126".

Do I need to compile this DLL myself? Do you have any instructions on how to do it?

Thank you!

**Comment by boyan01** [comment]
> Do I need to compile this DLL myself? 

No, you need not. Add deps to pubspec.yaml would be work. you can check the example directly.

I tested on my PC with flutter latest master channel, and can not reproduce this error.
